import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV generated by previous parsing
df = pd.read_csv('asa_summary.csv')

# Convert columns to appropriate types
df['radius'] = df['radius'].astype(float)
df['ASA_m2_per_g'] = df['ASA_m2_per_g'].astype(float)

# Separate data for each structure
mil = df[df['structure'] == 'MIL125']
bamof = df[df['structure'] == 'BAMOF']

# Create plot
plt.figure()
plt.plot(mil['radius'], mil['ASA_m2_per_cm3'], label='MIL-125-NH2')
plt.plot(bamof['radius'], bamof['ASA_m2_per_cm3'], label='BA-MOF')
plt.xlabel('Probe Radius (Å)')
plt.ylabel('Accessible Surface Area (m²/g)')
plt.title('ASA vs. Probe Radius for MIL-125 and BA-MOF')
plt.legend()
plt.tight_layout()
plt.show()
