# auto-generated by visualize_mof.py
set bg_rgb, [1.0,1.0,1.0]
load /mnt/d/PSID_BAMOF/try04/03_postprocessing/exported_cluster_ot_all/frame0029_2x2x2.mol2, frame0029_2x2x2

bg_color white
load frame0029_2x2x2
hide everything, all
show lines, all
set line_width, 1.2
set antialias, 2
set ray_shadows, 0
set depth_cue, 0
set specular, 0.2
set stick_h_scale, 1.0
set stick_radius, 0.12
set stick_ball, on
set line_as_cylinders, on
color gray60, elem C
color atomic, elem N
color red, elem O
color blue, elem N
color yellow, elem S
color green, elem F
hide everything, elem H
orient
zoom all, 2
set_view (
    0.7071,    0.0000,    0.7071,    0.0000,
    1.0000,    0.0000,   -0.7071,    0.0000,
   -0.7071,    0.7071,    0.0000,    0.0000,
    0.0000,    0.0000,   -100.0000,    1.0000
)
select framework, (elem Zr or elem Ti or elem Cu or elem Fe or elem Co or elem Ni or elem Al or elem Ti or elem Zn or elem Mg or elem Ca or elem Ba or elem Sr or elem Cd or elem In or elem Ga)
show spheres, framework
set sphere_scale, 0.40, framework
color marine, framework
